export type Project = {
 slug:string; number:string; category:string; title:string; shortDescription:string;
 problem:string; approach:string; solution:string; outcome:string; tags:string[];
};

export const projects:Project[]=[
 {slug:"operations-document-system",number:"01",category:"OPERATIONS / INFORMATION SYSTEMS",title:"Turning scattered operational documents into a working system.",shortDescription:"A structured digital workspace designed to organize documents, reports and operational information.",problem:"Operational information was distributed across documents, messages and different locations, making it harder to find information and maintain consistency.",approach:"Understand what information existed, how it was created and where it needed to move.",solution:"A centralized digital workspace organized around the actual operational workflow, with clearer organization, standardized information and easier access.",outcome:"A more structured foundation for managing operational information and reducing unnecessary friction.",tags:["Operations","Documentation","Information systems"]},
 {slug:"sports-operations",number:"02",category:"SPORTS / OPERATIONS",title:"Bringing structure to a complex sports operation.",shortDescription:"Planning, organizing and coordinating information across people, logistics and tournament requirements.",problem:"Sports operations can involve players, coaches, transportation, uniforms, documentation, budgets, schedules and multiple moving parts at the same time.",approach:"Break the operation into individual components so responsibilities, requirements and logistics can be tracked clearly.",solution:"Structured planning documents, tracking systems and operational workflows brought the different pieces together.",outcome:"A clearer operational structure for coordinating people, logistics and information.",tags:["Operations","Logistics","Planning","Reporting"]},
 {slug:"field-service-reporting",number:"03",category:"FIELD SERVICES / REPORTING",title:"Making field work easier to document and manage.",shortDescription:"A reporting workflow for capturing service information, materials and work performed.",problem:"Field service work produces information that needs to be captured accurately and communicated clearly.",approach:"Structure reporting around what managers, customers and administrative teams actually need.",solution:"A standardized reporting structure for service calls, personnel, scope of work and materials.",outcome:"More consistent documentation and a clearer connection between field work and administrative processes.",tags:["Reporting","Field Operations","Process Improvement"]}
];